// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXA4TAhAXa4zWZCjt0Vhu3tYAXSEKzpfM',
    appId: '1:791593793445:web:e2c6ee91c9d449d63d5a4c',
    messagingSenderId: '791593793445',
    projectId: 'canizares-firebase',
    authDomain: 'canizares-firebase.firebaseapp.com',
    storageBucket: 'canizares-firebase.firebasestorage.app',
    measurementId: 'G-MQ5YS2DL22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqMcm3t3grfRZnRjbzyGKiO9Gfssn3Z7g',
    appId: '1:791593793445:android:287b9480b1b956aa3d5a4c',
    messagingSenderId: '791593793445',
    projectId: 'canizares-firebase',
    storageBucket: 'canizares-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3jxsctGtbozyK4I2YLaiAdLqoq-qT8XU',
    appId: '1:791593793445:ios:a122478eacf5981d3d5a4c',
    messagingSenderId: '791593793445',
    projectId: 'canizares-firebase',
    storageBucket: 'canizares-firebase.firebasestorage.app',
    iosBundleId: 'com.example.canizaresAdvmobprog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3jxsctGtbozyK4I2YLaiAdLqoq-qT8XU',
    appId: '1:791593793445:ios:a122478eacf5981d3d5a4c',
    messagingSenderId: '791593793445',
    projectId: 'canizares-firebase',
    storageBucket: 'canizares-firebase.firebasestorage.app',
    iosBundleId: 'com.example.canizaresAdvmobprog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXA4TAhAXa4zWZCjt0Vhu3tYAXSEKzpfM',
    appId: '1:791593793445:web:c2e52ea9b1a1dbd43d5a4c',
    messagingSenderId: '791593793445',
    projectId: 'canizares-firebase',
    authDomain: 'canizares-firebase.firebaseapp.com',
    storageBucket: 'canizares-firebase.firebasestorage.app',
    measurementId: 'G-6R4V39E1TT',
  );
}
